name: CD
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.GH_RELEASE_TOKEN }}
#          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        - run: cargo install cargo-v
      - run: cargo v 0.2.0 -y
      - run: git commit -m "chore:release"
      - run: git push

#      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*