name: CD
on:
  push:
    branches:
      - main
env:
  VERSION: 0.0.0

jobs:
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-v
      - name: Update version
        run: echo "::set-output name=VERSION::$(echo cargo pkgid | cut -d# -f2 | cut -d":" -f2)"
        id: version
      - run: cargo v ${{ steps.version.outputs.VERSION }} -y
      - name: Set git user config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions@github.com
          git commit -m "chore:release"
          git push