name: CD
on:
  pull_request:
#    paths:
#      - "!.github/workflows/ci.yml"
    branches:
      - main
  push:
#    paths:
#      - "!.github/workflows/ci.yml"
    branches:
      - main

jobs:
  release:
    name: Release
    if: |
      (github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, 'release'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set Major version
        run: |
          echo "::set-output name=MAJOR::$(cargo pkgid | cut -d# -f2 | cut -d. -f1)"
          echo "::set-output name=MINOR::$(cargo pkgid | cut -d# -f2 | cut -d. -f2)"
          echo "::set-output name=PATCH::$(cargo pkgid | cut -d# -f2 | cut -d. -f3)"
        id: version
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.version.outputs.MAJOR }}.${{ steps.version.outputs.MINOR }}.${{ steps.version.outputs.PATCH }}
          version-fragment: 'bug' #Possible options are [ major | feature | bug | alpha | beta | rc ]
      - run: cargo install cargo-v
      - run: cargo v ${{ steps.bump_version.outputs.next-version }} -y
      - name: Set git user config
        run: |
          git config user.email ipetrovbg@gmail.com
          git config user.name Petar Petrov
          git commit -m "chore:bump version"
          git push
