name: CD
on:
  pull_request:
    branches:
      - main
env:
  VERSION: 0.0.0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - run: git pull
      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-v
      - run: cargo v 0.2.7 -y
      - name: Set git user config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions@github.com
          git commit -m "chore:release"
          git push origin HEAD:main