name: CD
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
    branches:
      - main
  push:
    paths:
      - ".github/workflows/ci.yml"
    branches:
      - main
env:
  MAJOR: 0
  MINOR: 2
  PATCH: 11

jobs:
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-v
      - run: cargo v ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }} -y
      - name: Set git user config
        run: |
          git config user.email ipetrovbg@gmail.com
          git config user.name Petar Petrov
          git commit -m "chore:bump version"
          git push
